### ISSUE TITLE
Some footnote links not found

### ISSUE THREAD

**Issue by kolibril13** [executablebooks/mystjs#225] opened 2023-02-16 12:40 UTC
### Which area is this feature request for?

Website User Interface

### Describe the feature you'd like to request

[On this page](https://myst-tools.org/docs/mystjs/quickstart-myst-markdown#typography) clicking on the expand footnote 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/44469195/219367019-f48f6205-e3d7-45a6-b32e-191423c09ca2.png">

will go to this link  https://myst-tools.org/mystjs/typography#footnotes 
which says: No Site Found

Same for 
https://myst-tools.org/mystjs/math#inline-math
https://myst-tools.org/mystjs/typography#definition-lists

**Comment by rowanc1** [comment] 2023-02-17 18:34
I am having trouble reproducing this. Are you saying that the `footnotes` link doesn't work? Or footnotes inside of there don't work? Or something else?!

Or the links don't work at all on your machine? Looks like there is a `docs` missing in the URL. Not sure how that would happen.

![image](https://user-images.githubusercontent.com/913249/219752980-91446770-43a2-40a0-ae78-2434d84229b7.png)

**Comment by kolibril13** [comment] 2023-02-17 18:41
This small button at the top right does not work:
<img width="87" alt="image" src="https://user-images.githubusercontent.com/44469195/219757103-58520a1a-f696-4ac8-8e64-d7a542aa2a87.png">

**Comment by rowanc1** [comment] 2023-02-17 18:59
Ah, perfect. Will fix that up, thank you!

**Comment by rowanc1** [comment] 2023-02-17 19:08
Fixed in https://github.com/executablebooks/myst-theme/pull/12

**Closed by rowanc1** 2023-02-17 19:08 UTC
Labels: story
